name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [created, published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install MUSL tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install wasm target
        shell: bash
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build
        run: cargo build --target x86_64-unknown-linux-musl --release

      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: target/release/uploader